- tenant:
    name: main
    max-nodes-per-job: 3
    max-job-timeout: 7200  # 2 hours
    web-root: https://zuul.teim.app/t/main

    source:
      github:
        config-projects:
          - SeanMooney/ci-sean-mooney:
              load-branch: main

        untrusted-projects:
          - SeanMooney/ci-jobs
          - SeanMooney/openstack-ai-style-guide

      opendev:
        untrusted-projects:
          - zuul/zuul-jobs
          - include: []
            projects:
              - opendev/bindep
              - opendev/git-review
              # devstack and tempest all define things expected
              # to be widely used.
              - openstack/devstack
              - openstack/tempest
              - openstack/adjutant
              - openstack/adjutant-ui
              - openstack/aetos
              - openstack/ansible-collection-kolla
              - openstack/ansible-collections-openstack
              - openstack/ansible-config_template
              - openstack/ansible-hardening
              - openstack/ansible-plugin-container-connection
              - openstack/ansible-role-atos-hsm
              - openstack/ansible-role-frrouting
              - openstack/ansible-role-httpd
              - openstack/ansible-role-lunasa-hsm
              - openstack/ansible-role-pki
              - openstack/ansible-role-proxysql
              - openstack/ansible-role-python_venv_build
              - openstack/ansible-role-systemd_mount
              - openstack/ansible-role-systemd_networkd
              - openstack/ansible-role-systemd_service
              - openstack/ansible-role-thales-hsm
              - openstack/ansible-role-uwsgi
              - openstack/ansible-role-vault
              - openstack/ansible-role-zookeeper
              - openstack/aodh
              - openstack/api-sig
              - openstack/api-site
              - openstack/arch-design
              - openstack/auto-scaling-sig
              - openstack/automaton
              - openstack/barbican
              - openstack/barbican-specs
              - openstack/barbican-tempest-plugin
              - openstack/barbican-ui
              - openstack/bashate
              - openstack/bifrost
              - openstack/blazar
              - openstack/blazar-dashboard
              - openstack/blazar-nova
              - openstack/blazar-specs
              - openstack/blazar-tempest-plugin
              - openstack/bugdaystats
              - openstack/castellan
              - openstack/ceilometer
              - openstack/ceilometermiddleware
              - openstack/ci-log-processing
              - openstack/cinder
              - openstack/cinder-specs
              - openstack/cinder-tempest-plugin
              - openstack/cinderlib
              - openstack/cliff
              - openstack/cloudkitty
              - openstack/cloudkitty-dashboard
              - openstack/cloudkitty-specs
              - openstack/cloudkitty-tempest-plugin
              - openstack/codegenerator
              - openstack/constellations
              - openstack/contributor-guide
              - openstack/cookiecutter
              - openstack/coverage2sql
              - openstack/cyborg
              - openstack/cyborg-specs
              - openstack/cyborg-tempest-plugin
              - openstack/debtcollector
              - openstack/designate
              - openstack/designate-dashboard
              - openstack/designate-specs
              - openstack/designate-tempest-plugin
              - openstack/devstack-plugin-amqp1
              - openstack/devstack-plugin-ceph
              - openstack/devstack-plugin-container
              - openstack/devstack-plugin-cookiecutter
              - openstack/devstack-plugin-kafka
              - openstack/devstack-plugin-nfs
              - openstack/devstack-plugin-open-cas
              - openstack/devstack-plugin-prometheus
              - openstack/devstack-tools
              - openstack/devstack-vagrant
              - openstack/diskimage-builder
              - openstack/election
              - openstack/eslint-config-openstack
              - openstack/etcd3gw
              - openstack/freezer
              - openstack/freezer-api
              - openstack/freezer-specs
              - openstack/freezer-tempest-plugin
              - openstack/freezer-web-ui
              - openstack/futurist
              - openstack/glance
              - openstack/glance-specs
              - openstack/glance-tempest-plugin
              - openstack/glance_store
              - openstack/goal-tools
              - openstack/governance
              - openstack/governance-sigs
              - openstack/governance-website
              - openstack/grenade
              - openstack/grian-ui
              - openstack/ha-guide
              - openstack/hacking
              - openstack/heat
              - openstack/heat-agents
              - openstack/heat-cfntools
              - openstack/heat-dashboard
              - openstack/heat-specs
              - openstack/heat-tempest-plugin
              - openstack/heat-templates
              - openstack/heat-translator
              - openstack/horizon
              - openstack/i18n
              - openstack/ideas
              - openstack/ironic
              - openstack/ironic-inspector
              - openstack/ironic-inspector-specs
              - openstack/ironic-lib
              - openstack/ironic-prometheus-exporter
              - openstack/ironic-python-agent
              - openstack/ironic-python-agent-builder
              - openstack/ironic-specs
              - openstack/ironic-tempest-plugin
              - openstack/ironic-ui
              - openstack/karma-subunit-reporter
              - openstack/kayobe
              - openstack/kayobe-config
              - openstack/kayobe-config-dev
              - openstack/keystone
              - openstack/keystone-specs
              - openstack/keystone-tempest-plugin
              - openstack/keystoneauth
              - openstack/keystonemiddleware
              - openstack/kolla
              - openstack/kolla-ansible
              - openstack/kuryr
              - openstack/kuryr-kubernetes
              - openstack/kuryr-libnetwork
              - openstack/kuryr-tempest-plugin
              - openstack/large-scale
              - openstack/ldappool
              - openstack/liberasurecode
              - openstack/loci
              - openstack/logstash-filters
              - openstack/magnum
              - openstack/magnum-capi-helm
              - openstack/magnum-capi-helm-charts
              - openstack/magnum-specs
              - openstack/magnum-tempest-plugin
              - openstack/magnum-ui
              - openstack/manila
              - openstack/manila-image-elements
              - openstack/manila-specs
              - openstack/manila-tempest-plugin
              - openstack/manila-test-image
              - openstack/manila-ui
              - openstack/masakari
              - openstack/masakari-dashboard
              - openstack/masakari-monitors
              - openstack/masakari-specs
              - openstack/metalsmith
              - openstack/microversion-parse
              - openstack/mistral
              - openstack/mistral-dashboard
              - openstack/mistral-extra
              - openstack/mistral-lib
              - openstack/mistral-specs
              - openstack/mistral-tempest-plugin
              - openstack/molteniron
              - openstack/monasca-agent
              - openstack/monasca-api
              - openstack/monasca-ceilometer
              - openstack/monasca-common
              - openstack/monasca-events-api
              - openstack/monasca-grafana-datasource
              - openstack/monasca-kibana-plugin
              - openstack/monasca-log-api
              - openstack/monasca-notification
              - openstack/monasca-persister
              - openstack/monasca-specs
              - openstack/monasca-statsd
              - openstack/monasca-tempest-plugin
              - openstack/monasca-thresh
              - openstack/monasca-transform
              - openstack/monasca-ui
              - openstack/multi-arch-sig
              - openstack/networking-bagpipe
              - openstack/networking-baremetal
              - openstack/networking-bgpvpn
              - openstack/networking-generic-switch
              - openstack/networking-midonet
              - openstack/networking-odl
              - openstack/networking-sfc
              - openstack/neutron
              - openstack/neutron-dynamic-routing
              - openstack/neutron-fwaas
              - openstack/neutron-fwaas-dashboard
              - openstack/neutron-lib
              - openstack/neutron-specs
              - openstack/neutron-tempest-plugin
              - openstack/neutron-vpnaas
              - openstack/neutron-vpnaas-dashboard
              - openstack/nose-html-output
              - openstack/nova
              - openstack/nova-specs
              - openstack/octavia
              - openstack/octavia-dashboard
              - openstack/octavia-lib
              - openstack/octavia-tempest-plugin
              - openstack/openapi
              - openstack/openstack
              - openstack/openstack-doc-tools
              - openstack/openstack-manuals
              - openstack/openstack-nose
              - openstack/openstack-planet
              - openstack/openstackclient
              - openstack/openstackdocstheme
              - openstack/openstacksdk
              - openstack/operations-guide
              - openstack/os-api-ref
              - openstack/os-apply-config
              - openstack/os-brick
              - openstack/os-client-config
              - openstack/os-collect-config
              - openstack/os-ken
              - openstack/os-performance-tools
              - openstack/os-refresh-config
              - openstack/os-resource-classes
              - openstack/os-service-types
              - openstack/os-test-images
              - openstack/os-testr
              - openstack/os-traits
              - openstack/os-vif
              - openstack/osc-lib
              - openstack/osc-placement
              - openstack/oslo-cookiecutter
              - openstack/oslo-specs
              - openstack/oslo.cache
              - openstack/oslo.concurrency
              - openstack/oslo.config
              - openstack/oslo.context
              - openstack/oslo.db
              - openstack/oslo.i18n
              - openstack/oslo.limit
              - openstack/oslo.log
              - openstack/oslo.messaging
              - openstack/oslo.metrics
              - openstack/oslo.middleware
              - openstack/oslo.policy
              - openstack/oslo.privsep
              - openstack/oslo.reports
              - openstack/oslo.rootwrap
              - openstack/oslo.serialization
              - openstack/oslo.service
              - openstack/oslo.tools
              - openstack/oslo.upgradecheck
              - openstack/oslo.utils
              - openstack/oslo.versionedobjects
              - openstack/oslo.vmware
              - openstack/oslotest
              - openstack/osops
              - openstack/osprofiler
              - openstack/ossa
              - openstack/ovn-bgp-agent
              - openstack/ovn-octavia-provider
              - openstack/ovsdbapp
              - openstack/panko
              - openstack/pbr
              - openstack/performance-docs
              - openstack/placement
              - openstack/project-team-guide
              - openstack/ptgbot
              - openstack/publiccloud-sig
              - openstack/pycadf
              - openstack/pyeclib
              - openstack/pymod2pkg
              - openstack/python-adjutantclient
              - openstack/python-aodhclient
              - openstack/python-barbicanclient
              - openstack/python-blazarclient
              - openstack/python-brick-cinderclient-ext
              - openstack/python-cinderclient
              - openstack/python-cloudkittyclient
              - openstack/python-cyborgclient
              - openstack/python-designateclient
              - openstack/python-dracclient
              - openstack/python-freezerclient
              - openstack/python-glanceclient
              - openstack/python-heatclient
              - openstack/python-ironic-inspector-client
              - openstack/python-ironicclient
              - openstack/python-keystoneclient
              - openstack/python-magnumclient
              - openstack/python-manilaclient
              - openstack/python-masakariclient
              - openstack/python-mistralclient
              - openstack/python-monascaclient
              - openstack/python-neutronclient
              - openstack/python-novaclient
              - openstack/python-observabilityclient
              - openstack/python-octaviaclient
              - openstack/python-openstackclient
              - openstack/python-pankoclient
              - openstack/python-swiftclient
              - openstack/python-tackerclient
              - openstack/python-troveclient
              - openstack/python-venusclient
              - openstack/python-vitrageclient
              - openstack/python-watcherclient
              - openstack/python-zaqarclient
              - openstack/python-zunclient
              - openstack/qa-specs
              - openstack/rally
              - openstack/rally-openstack
              - openstack/rbd-iscsi-client
              - openstack/release-test
              - openstack/releases
              - openstack/renderspec
              - openstack/reno
              - openstack/requestsexceptions
              - openstack/requirements
              - openstack/reviewday
              - openstack/reviewstats
              - openstack/rpm-packaging
              - openstack/rpm-packaging-tools
              - openstack/security-doc
              - openstack/self-healing-sig
              - openstack/service-types-authority
              - openstack/shade
              - openstack/skyline-apiserver
              - openstack/skyline-console
              - openstack/specs-cookiecutter
              - openstack/sphinx-feature-classification
              - openstack/stackviz
              - openstack/stevedore
              - openstack/storlets
              - openstack/sunbeam-charms
              - openstack/sushy
              - openstack/sushy-oem-idrac
              - openstack/sushy-tools
              - openstack/swift
              - openstack/swift-bench
              - openstack/tacker
              - openstack/tacker-horizon
              - openstack/tacker-specs
              - openstack/tap-as-a-service
              - openstack/taskflow
              - openstack/telemetry-specs
              - openstack/telemetry-tempest-plugin
              - openstack/tempest-plugin-cookiecutter
              - openstack/tempest-stress
              - openstack/tenks
              - openstack/tooz
              - openstack/tosca-parser
              - openstack/training-guides
              - openstack/tripleo-ci
              - openstack/tripleo-ci-health-queries
              - openstack/trove
              - openstack/trove-dashboard
              - openstack/trove-specs
              - openstack/trove-tempest-plugin
              - openstack/ui-cookiecutter
              - openstack/upstream-institute-virtual-environment
              - openstack/venus
              - openstack/venus-dashboard
              - openstack/venus-specs
              - openstack/venus-tempest-plugin
              - openstack/virtualbmc
              - openstack/virtualpdu
              - openstack/vitrage
              - openstack/vitrage-dashboard
              - openstack/vitrage-specs
              - openstack/vitrage-tempest-plugin
              - openstack/watcher
              - openstack/watcher-dashboard
              - openstack/watcher-specs
              - openstack/watcher-tempest-plugin
              - openstack/whereto
              - openstack/whitebox-tempest-plugin
              - openstack/xstatic-angular
              - openstack/xstatic-angular-bootstrap
              - openstack/xstatic-angular-fileupload
              - openstack/xstatic-angular-gettext
              - openstack/xstatic-angular-lrdragndrop
              - openstack/xstatic-angular-material
              - openstack/xstatic-angular-notify
              - openstack/xstatic-angular-smart-table
              - openstack/xstatic-angular-uuid
              - openstack/xstatic-angular-vis
              - openstack/xstatic-bootstrap-datepicker
              - openstack/xstatic-bootstrap-scss
              - openstack/xstatic-bootswatch
              - openstack/xstatic-d3
              - openstack/xstatic-dagre
              - openstack/xstatic-dagre-d3
              - openstack/xstatic-filesaver
              - openstack/xstatic-graphlib
              - openstack/xstatic-hogan
              - openstack/xstatic-jasmine
              - openstack/xstatic-jquery-migrate
              - openstack/xstatic-jquery.quicksearch
              - openstack/xstatic-jquery.tablesorter
              - openstack/xstatic-js-yaml
              - openstack/xstatic-jsencrypt
              - openstack/xstatic-json2yaml
              - openstack/xstatic-lodash
              - openstack/xstatic-magic-search
              - openstack/xstatic-mdi
              - openstack/xstatic-moment
              - openstack/xstatic-moment-timezone
              - openstack/xstatic-rickshaw
              - openstack/xstatic-roboto-fontface
              - openstack/xstatic-spin
              - openstack/yaql
              - openstack/zaqar
              - openstack/zaqar-specs
              - openstack/zaqar-tempest-plugin
              - openstack/zaqar-ui
              - openstack/zun
              - openstack/zun-tempest-plugin
              - openstack/zun-ui
              
