- tenant:
    name: main
    max-nodes-per-job: 3
    max-job-timeout: 7200  # 2 hours
    web-root: https://zuul.teim.app/t/main

    source:
      github:
        config-projects:
          - SeanMooney/ci-sean-mooney:
              load-branch: main

        untrusted-projects:
          - SeanMooney/ci-jobs
          - SeanMooney/openstack-ai-style-guide

      opendev:
        untrusted-projects:
          - zuul/zuul-jobs
          - include: []
            projects:
              - opendev/bindep
              - opendev/git-review
              # devstack and tempest all define things expected
              # to be widely used.
              - openstack/devstack
              - openstack/tempest
              - openstack/adjutant
              - openstack/adjutant-ui
              - openstack/aetos
              - openstack/aodh
              - openstack/castellan
              - openstack/ceilometer
              - openstack/ceilometermiddleware
              - openstack/cinder
              - openstack/cinder-specs
              - openstack/cinder-tempest-plugin
              - openstack/cinderlib
              - openstack/cliff
              - openstack/cloudkitty
              - openstack/cloudkitty-dashboard
              - openstack/cloudkitty-specs
              - openstack/cloudkitty-tempest-plugin
              - openstack/cyborg
              - openstack/cyborg-specs
              - openstack/cyborg-tempest-plugin
              - openstack/devstack-plugin-amqp1
              - openstack/devstack-plugin-ceph
              - openstack/devstack-plugin-container
              - openstack/devstack-plugin-nfs
              - openstack/devstack-plugin-prometheus
              - openstack/devstack-tools
              - openstack/diskimage-builder
              - openstack/etcd3gw
              - openstack/futurist
              - openstack/glance
              - openstack/glance-specs
              - openstack/glance-tempest-plugin
              - openstack/glance_store
              - openstack/grenade
              - openstack/grian-ui
              - openstack/horizon
              - openstack/ironic
              - openstack/ironic-inspector
              - openstack/ironic-inspector-specs
              - openstack/ironic-lib
              - openstack/ironic-prometheus-exporter
              - openstack/ironic-python-agent
              - openstack/ironic-python-agent-builder
              - openstack/ironic-specs
              - openstack/ironic-tempest-plugin
              - openstack/ironic-ui
              - openstack/keystone
              - openstack/keystone-specs
              - openstack/keystone-tempest-plugin
              - openstack/keystoneauth
              - openstack/keystonemiddleware
              - openstack/neutron
              - openstack/neutron-dynamic-routing
              - openstack/neutron-fwaas
              - openstack/neutron-fwaas-dashboard
              - openstack/neutron-lib
              - openstack/neutron-specs
              - openstack/neutron-tempest-plugin
              - openstack/neutron-vpnaas
              - openstack/neutron-vpnaas-dashboard
              - openstack/nova
              - openstack/nova-specs
              - openstack/openstackclient
              - openstack/openstackdocstheme
              - openstack/openstacksdk
              - openstack/os-brick
              - openstack/os-resource-classes
              - openstack/os-service-types
              - openstack/os-test-images
              - openstack/os-traits
              - openstack/os-vif
              - openstack/osc-lib
              - openstack/osc-placement
              - openstack/oslo-specs
              - openstack/oslo.cache
              - openstack/oslo.concurrency
              - openstack/oslo.config
              - openstack/oslo.context
              - openstack/oslo.db
              - openstack/oslo.i18n
              - openstack/oslo.limit
              - openstack/oslo.log
              - openstack/oslo.messaging
              - openstack/oslo.metrics
              - openstack/oslo.middleware
              - openstack/oslo.policy
              - openstack/oslo.privsep
              - openstack/oslo.reports
              - openstack/oslo.rootwrap
              - openstack/oslo.serialization
              - openstack/oslo.service
              - openstack/oslo.tools
              - openstack/oslo.upgradecheck
              - openstack/oslo.utils
              - openstack/oslo.versionedobjects
              - openstack/oslo.vmware
              - openstack/oslotest
              - openstack/ovn-bgp-agent
              - openstack/ovsdbapp
              - openstack/pbr
              - openstack/placement
              - openstack/python-aodhclient
              - openstack/python-barbicanclient
              - openstack/python-brick-cinderclient-ext
              - openstack/python-cinderclient
              - openstack/python-cloudkittyclient
              - openstack/python-cyborgclient
              - openstack/python-glanceclient
              - openstack/python-ironic-inspector-client
              - openstack/python-ironicclient
              - openstack/python-keystoneclient
              - openstack/python-neutronclient
              - openstack/python-novaclient
              - openstack/python-observabilityclient
              - openstack/python-openstackclient
              - openstack/python-swiftclient
              - openstack/python-watcherclient
              - openstack/reno
              - openstack/requirements
              - openstack/stevedore
              - openstack/swift
              - openstack/swift-bench
              - openstack/taskflow
              - openstack/telemetry-specs
              - openstack/telemetry-tempest-plugin
              - openstack/tempest-plugin-cookiecutter
              - openstack/watcher
              - openstack/watcher-dashboard
              - openstack/watcher-specs
              - openstack/watcher-tempest-plugin
              - openstack/whitebox-tempest-plugin
              
