- tenant:
    name: main
    max-nodes-per-job: 3
    max-job-timeout: 7200  # 2 hours
    web-root: https://zuul.teim.app/t/main

    source:
      github:
        config-projects:
          - SeanMooney/ci-sean-mooney:
              load-branch: main

        untrusted-projects:
          - SeanMooney/ci-jobs
          - SeanMooney/openstack-ai-style-guide

      opendev:
        untrusted-projects:
          - zuul/zuul-jobs
          - include: []
            projects:
              - openstack/watcher
              - openstack/watcher-dashboard
              - openstack/watcher-tempest-plugin
              - openstack/python-watcherclient
              - openstack/nova
              - openstack/placement
              - openstack/ironic
              - openstack/devstack
              - openstack/cyborg
              - openstack/neutron
              - openstack/keystone
              - openstack/glance
              - openstack/cinder
              - openstack/swift
              - openstack/heat
              - openstack/barbican
              - openstack/ceilometer
              - openstack/aetos
              